export const INCREMENT_NUM = "INCREMENT_NUM"
export const DECREMENT_NUM = "DECREMENT_NUM"
export const COUNTER_ACTION_START = "COUNTER_ACTION_START"
export const COUNTER_ACTION_FINISH = "COUNTER_ACTION_FINISH"